/*
 * Leave Module API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// Get all leave requests
        /// </summary>
        /// <response code="200">A list of leave requests</response>
        [HttpGet]
        [Route("/aes-3ef/LeaveModule/1.0.0/leaveRequests")]
        [ValidateModelState]
        [SwaggerOperation("LeaveRequestsGet")]
        public virtual IActionResult LeaveRequestsGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Submit a leave request
        /// </summary>
        /// <param name="body"></param>
        /// <response code="201">Leave request created</response>
        [HttpPost]
        [Route("/aes-3ef/LeaveModule/1.0.0/leaveRequests")]
        [ValidateModelState]
        [SwaggerOperation("LeaveRequestsPost")]
        public virtual IActionResult LeaveRequestsPost([FromBody]LeaveRequest body)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            throw new NotImplementedException();
        }
    }
}
